### ISSUE TITLE
Zeldovich.py

### ISSUE THREAD

**Issue by Ispahan** [faldah/computationalAstrophysics#1]
Hello,

I have tried to run your program, specifically the zeldovich.py file however I get
this error which I can not fix:

Traceback (most recent call last):
  File "zeldovich.py", line 254, in <module>
    evolve(xini, yini, zini, pxini, pyini, pzini, aini, da)
  File "zeldovich.py", line 217, in evolve
    xp = x_array[i,:,N/2,N/2]
NameError: global name 'x_array' is not defined

Maybe you know how to fix it?

**Comment by Ispahan** [comment]
Hello,

I have tried several things to fix the problem including redefining 
the x,y,z array and defining i. However the problem still exists.
Could you please take a look at this problem?

**Comment by therealfrs** [comment]
You are absolutely right. I on it.

**Comment by Ispahan** [comment]
Thank you for looking into it.
Can you let me know when you figure out the problem?
Thank you so moch.
Cheers.

2015-07-03 9:17 GMT+02:00 Feras Aldahlawi notifications@github.com:

**Comment by therealfrs** [comment]
I have fixed some of the problems. Now it will display the plots instead of saving it to a file.

**Comment by Ispahan** [comment]
I don´t seen any plots when I run the zeldovich.py. Instead I get this error:
Traceback (most recent call last):
  File "zeldovich.py", line 255, in <module>
    xini,yini,zini,pxini,pyini,pzini, phiini, gxini = zeldovich(aini,da)
TypeError: 'NoneType' object is not iterable

Do you know why?
I´ like to see how your zeldovich.py file generates the plots I have seen
in the: Zeldovich folder.

**Comment by therealfrs** [comment]
That is strange. Do you have all other files in the same location as the repository? Also, do you have numpy, scipy installed?

**Comment by Ispahan** [comment]
Yes I have all these packages which you call in your code.
The problem seems to be in the last few lines of the code ´Test´
When I remove them, the code seems to be running, my terminal returns
no errors but returns normally. However I see no plots or evidence that 
the program did anything.
Is there another way to plot whatever is computed in the zeldovich.py file?

**Comment by Ispahan** [comment]
I have the same problem with the vort.py file. I run it but my terminal 
returns the directory without doing anything. 
I don´t understand why no plots are shown and if they are saved where they go.

**Comment by therealfrs** [comment]
I have update the Zeldocich.py file such that it plots and doesn't save to a file. You can do the same to the vort.py file by changing the ply.savefig to plt.show( ).

But I don't know why you are having issues with plotting.

**Comment by Ispahan** [comment]
Hello again,

When I run the zeldovich.py my terminal finishes in 1 sec and then returns silently.
it is as if nothing was computed. Same with the vort.py and the cosmology.py.
I really have no idea what could be wrong?
It seems to do something but I see nothing, also no errors are given.

**Comment by therealfrs** [comment]
I think now it will work.

But there is another issue that I need to figure out again. It seems that my simulation and analytical part are off by some factor (I suspect this is due to the conversion from physical units to code units)

**Comment by Ispahan** [comment]
Yes it does Thank you, it is finally plotting!
And you are right there is still a problem; the numerical and analytical 
part are not overlapping.

**Comment by Ispahan** [comment]
Do you have any idea how to solve this?

**Comment by Ispahan** [comment]
Hello again,

Have you looked into the analytical solution problem?

Cheers
